apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: db
  labels:
    progetto: menu
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "CAMBIAMI"
  MYSQL_DATABASE: "menu"
  MYSQL_USER: "menu_user"
  MYSQL_PASSWORD: "CAMBIAMI"
